version: "2"

services:
  static:
    image: nginx:stable
    container_name: django_seevo_static
    ports:
      - "80:80"
    volumes:
      - seevo_static_data:/var/www/static
      - ./conf:/etc/nginx/conf.d
    env_file:
      - env_files/.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    networks:
      django_seevo_net:
        aliases:
          - django_seevo_static

  app:
    build:
      context: .
    container_name: django_seevo_app
    expose:
      - 8000
    volumes:
      - seevo_static_data:/opt/Hacku/webapp/static
      - seevo_app_data:/opt/Hacku/webapp/data
    env_file:
      - env_files/.env
    restart: always
    networks:
      django_seevo_net:
        aliases:
          - django_seevo_app

networks:
  django_seevo_net:

volumes:
  seevo_static_data:
  seevo_app_data: