# Generated by Django 2.1 on 2018-08-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidetable',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='slide end time'),
        ),
    ]
