# Generated by Django 2.1 on 2018-08-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20180828_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.RoomTable')),
            ],
        ),
    ]
