# Generated by Django 2.1 on 2018-08-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20180828_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttable',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='votetable',
            name='room_id',
        ),
    ]
