# Generated by Django 2.1 on 2018-08-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_listenertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenertable',
            name='listener_ip',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
